[files]
extend-exclude = ["*.age", "*.crypt", "nix/home.nix"]
ignore-vcs = true

[default]
extend-ignore-re = [".*sha256 = \".*\""]

[default.extend-words]
Sur = "Sur"
airborn = "airborn"
crypted = "crypted"
edn = "edn"
